---

- name: Check if tenancy already exists
  shell: PATH=$PATH:/usr/local/bin oc get projects -l tenancy={{ tenancy|lower }} --token={{ ocp_token }}
  register: cr
  changed_when: False

- name: Create projects in tenancy
  shell: PATH=$PATH:/usr/local/bin oc new-project {{ tenancy|lower }}-{{ item|lower }} --token={{ ocp_token }}
  with_items: "{{ projects }}"
  when: "'No resources found' in cr.stderr"

- name: Label projects in tenancy
  shell: PATH=$PATH:/usr/local/bin oc label namespace {{ tenancy|lower }}-{{ item|lower }} tenancy={{ tenancy|lower }} --token={{ ocp_token }}
  with_items: "{{ projects }}"
  when: "'No resources found' in cr.stderr"